############################################################################
# Contest 2026 team 455 angle control app - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = angle_control
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_455_ANGLE_CONTROL)

MAINSRC = angle_control_main.c

include $(APPDIR)/Application.mk
